### ISSUE TITLE
Track Extensions Causing Issue

### ISSUE THREAD

**Issue by LegendaryOverlord** [kkkrist/chromium-notifier#20]
If I enable the "Track Extensions" option, the menu no longer shows up. Clicking on the icon will produce a small, thin, blank menu. Also, there is no #extension-mime-request-handling flag to change. I'm using Win64-stable Chromium 78.0.3904.70.

**Comment by kkkrist** [comment]
Thank you for bringing this up! Could you right-click in that blank popup window, select "Inspect" and post any error messages that appear on the console tab? Alternatively, errors are also shown on `chrome://extensions/`.

I've rewritten the whole popup window and made state handling much more robust, see #18. I'm currently testing it (damn, there haven't been any updates since I do 🙃) and could post a beta here for you to see if it fixes the error.

As for `#extension-mime-request-handling`, this seems to be patched in by some Chromium builds. I'm pretty new to the Chromium scene, will have to investigate and update README accordingly.

**Comment by LegendaryOverlord** [comment]
No problem. This is what I get:

Uncaught TypeError: Cannot read property 'endsWith' of undefined
    at popup.js:174
    at Array.map (<anonymous>)
    at ExtensionsInfo (popup.js:138)
    at view (popup.js:352)
    at render (hyperapp-2.0.2.js:482)

If you post the beta, I'll install it and let you know if it fixes the issue.

**Comment by kkkrist** [comment]
Thanks! It seems like the update info you're receiving for one or more of your installed extensions has an unexpected format. The new version won't guard against it as well and throw the same error.

Could you show me the blob you get from the [proxy](https://github.com/kkkrist/chromium-extension-service)? Just type `localStorage.extensionsInfo` into the aforementioned console and copy+paste the whole stringified json object you'll get. If you don't want to share it here publicly, you could send me an email at `github at mundpropaganda.net`

**Comment by kkkrist** [comment]
I ran some queries and found a few instances where the update-url endpoint replies with a "noupdate" status and omits the codebase url. That's probably the culprit.
 
Would you mind trying out the attached version and see if it fixes the problem? Thanks!

[chrome-notifier-v1.5.0rc2.crx.zip](https://github.com/kkkrist/chromium-notifier/files/3773552/chrome-notifier-v1.5.0rc2.crx.zip)

**Comment by LegendaryOverlord** [comment]
That appears to have fixed it. It looks like I'm getting the full menu, and clicking on a new version number prompts a download. Nice work.
