### ISSUE TITLE
Don't work since Monday. Any idea?

### ISSUE THREAD

**Issue by CBearr** [kkkrist/chromium-notifier#37]
Don't work since Monday. Any idea?
I updated now manually to Build #4646
I disabled the extension and activated it... no update of the last search from Monday the 13th
![Screenshot 2021-09-17 161356](https://user-images.githubusercontent.com/82800336/133797631-1d0847b3-8e1e-425a-bf7d-2c0db2de5c25.jpg)

**Comment by kkkrist** [comment]
Hey,

thanks for reporting this! These type of errors are indeed increasingly registered by the error tracker, sometimes 100+ per day.

It should only happen when "track extension updates" is enabled together with "increase privacy". When that's the case, requests to the Chrome Web Store are routed through [our privacy proxy](https://github.com/kkkrist/chromium-extension-service). Requests to the Woolyss API are still sent directly, but might get cancelled should previous requests fail.

However, "track extension updates" is disabled on your screenshot. Have you had it enabled before?

The root cause seems to be the hosting setup of the proxy (Vercel/MongoDB Atlas) running over capacity once again. I don't think there's much room for optimization left, also I don't think I'm willing to pay for a higher tier.

(I never thought this project would have so many users one day 😀)

**Comment by CBearr** [comment]
Now it works again. And just checked for updates. Maybe your proxy have reset the traffic?
Yes, I activated track extension updates and increase privacy the whole time. I deactivated it just before I wrote this thread to try to solve the issue. But didn't solved it last Friday.
If I don't need track extension updates I'll deactivate this function.

**Comment by kkkrist** [comment]
The traffic shouldn't be the problem, it's the execution time limit. The proxy is made up of "serverless" functions running via Vercel. The current plan limits execution time to 5 seconds. This seems to be increasingly exceeded when the database needs to be accessed (which is hosted on MongoDB Atlas).

My testing consistently shows 500-700 ms response time on a cold start and 100-150 ms when hot (I'm routed to Frankfurt/M). Since I haven't done any changes to how the proxy works for 2 years and these errors were super rare before (and I don't keep any logs on purpose), I can only guess this happens due to increased load (at times).
