### ISSUE TITLE
How to solve: No update info available

### ISSUE THREAD

**Issue by Offerel** [kkkrist/chromium-notifier#38]
I have created a WebExtension, but i really don't want to publish this Extension in the Chrome Store. Is a publication in the store required, when i want to check for Extension updates? I Have tried to use your extension as a template and have added "update_url" in manifest.json pointing to a XML file in https://raw.githubusercontent.com/..., the file is available and the URL works, but the message "No update info available" is not gone yet. Can you please give some hints, how i can solve this?

**Comment by kkkrist** [comment]
From the top of my head:

You need to have a url to your [`gupdate.xml`](https://github.com/kkkrist/chromium-notifier/blob/master/gupdate.xml) file included as `update_url` in your [`manifest.json`](https://github.com/kkkrist/chromium-notifier/blob/master/manifest.json). The `version` from the manifest will then be compared to the `version` attribute of the `updatecheck` tag of the xml. If they differ, a update notification will be triggered.

Can I see the repo of your extension?

**Comment by Offerel** [comment]
Sure, you will find it at https://github.com/Offerel/SyncMarks-Extension. I have updated master some minutes ago, to reflect my changes.

**Comment by kkkrist** [comment]
That looks alright actually. I'll see if I can find time to do some testing.

**Comment by Offerel** [comment]
Nice. Only if you have the time... I wish, i could use such an extension also on mobile, but for now, only Kiwi supports these but the Chromium base is a little bit outdated there. My extension works also on Firefox Android, but without the bookmark API its usage is limited.

**Comment by kkkrist** [comment]
So first of all, there was a problem with the [privacy proxy](https://github.com/kkkrist/chromium-extension-service). If you had it turned on, it would time out very often (since circa end of August). The request handler had some simple memoization built-in to keep database load in check. Unfortunately, there are now so many users using so many different extensions on many different Chromium versions that this would often exceed memory limits. I've thrown memoization out and it seems to work reliably again. Let's see how the database setup handles the increased load now.

Second (and this is likely the actual cause), the extension update data is matched using the `id`. As long as you're installing from signed packages via the store or from .crx files, the extension will keep having the same `id` and it works fine. If you install via "Load unpacked extension" however, the installed extension will get a random new `id` each time and my extension won't be able to match the info. Can this be the reason it doesn't work for you?

I know this is quite unfortunate because unlisted extensions seem to only be installable via this method under many circumstances. But I don't see any other extension attribute unique enough for this purpose. Maybe I could use `homepageUrl` for unlisted extensions? I have to think about it.

**Comment by kkkrist** [comment]
Yes, that's it. When I install your extension via the signed .crx attached to the release, it works because it keeps the `id` that's found in your `gupdate.xml`.

I've just pushed an update (v1.8.6) which uses `updateUrl` as a fallback to `id` when matching update info. With that it works even if an extension is installed via "Load unpacked extension".

Can you confirm?

(Edit: this will only work if a static `updateUrl` is used like both our extensions do)

**Comment by Offerel** [comment]
Yes, I can confirm that this is working as expected. Many thx for the update.
