### ISSUE TITLE
MacOS ARM Platform

### ISSUE THREAD

**Issue by mvicari** [kkkrist/chromium-notifier#44]
Would it be possible to add and track the [Chromium for 64-bit macOS on Arm](https://chromium.woolyss.com/#mac-on-arm)? Not currently supported.

**Comment by kkkrist** [comment]
@woolyss Hey Jerry, could you add those on the API endpoint? The extension should pick them up automatically once you did.

**Comment by ghost** [comment]
Hello guys,
There is the link to the release of "The Chromium Authors"... but not about the AlexFrick release because he currently does not use our API :/

**Comment by kkkrist** [comment]
Ok. I'll look into integrating it via the GitHub API. Might take a while until I find the time though.

**Comment by mvicari** [comment]
@Alex313031 is this something you might be able to look into/incorporate?

**Comment by Alex313031** [comment]
@woolyss @mvicari Hey, Jerry, I honestly just didn't know what to do with the information given when you emailed me about using your API. I would be perfectly fine using your API so that it would show the version and link directly to files instead of "Binaries". Just need someone to guide me through like a baby on what to do, and how to update when I make new releases.

I'm dumb when it comes to that stuff. I have a very unique set of skills in development. I work on Chromium, ChromiumOS, and bash scripts/python scripts. I know close to nothing about web stuff. I know a decent amount *about* web technologies, like what they do, but not how to actually implement them. For example, the most I've done with web dev is make a text website with a picture, background, and button to change the background lol. So when you gave me this link in email > https://chromium.woolyss.com/upload/info.php I didn't know what to do with it. Are get and post requests something I can do right in bash? Please swaddle my ignorant ass in your webmaster blanket lol.

**Comment by kkkrist** [comment]
> Are get and post requests something I can do right in bash? Please swaddle my ignorant ass in your webmaster blanket lol.

I don't know anything about this specific API, but you'd need something like curl to call REST APIs from a bash script :-)

Here's an example for a POST call to a json-based API:
```sh
$ curl -X POST https://api.tld/endpoint -H 'Content-Type: application/json' -d '{"key1":"value1","key2":"value2"}'
```

**Comment by kkkrist** [comment]
@Alex313031 Is using the Woolyss API something you still want to do?

I've looked into tracking your releases via the GitHub API, but I don't think this would be very robust given how things currently work.

We'd need to filter out the right releases by grepping the release `name` (title) and/or `body` for keywords (e.g. "M1"). Changing the naming scheme could easily break the updater.

Additionally, I'd need to rewrite the data fetching logic to make it possible to only fetch from the GitHub API if the user has actually chosen to track your builds. This extension is basically in maintenance mode, so I'm not overly keen on touching it ;-)
