### ISSUE TITLE
Update logo and publishing.

### ISSUE THREAD

**Issue by Alex313031** [kkkrist/chromium-notifier#47]
Hi, firstly the logos should be updated to reflect the new Chromium logo. Second, why have you not published this to the chrome web store. I recently made an account, and have added these extensions.
https://chrome.google.com/webstore/detail/chromium-vector-icon-pain/cnlndebkegcfnbiknohgneobakigplhf
https://chrome.google.com/webstore/detail/crunchbangplusplus-scroll/mfindlbbleadbcpkgbkbfojnghelnfil
https://chrome.google.com/webstore/detail/cog-system-info-viewer/bkapefioegaebnkbjpfbbemmmcholeii
https://chrome.google.com/webstore/detail/thorium-scrollbars/ilhogmofjjmlbjoceipichhgfnnbldcn
https://chrome.google.com/webstore/detail/thorium-material-dark-the/dahfohiipmpcppjbablgfoggbogdmddp

I can update the logos and publish it for you, as well as update it to manifest v3 so that it will continue working in the future.

**Comment by kkkrist** [comment]
Thank you for your suggestions!

Feel free to send a PR updating the logo. I kind of missed it, because frankly speaking, I've stopped daily-driving Chromium community builds and this extension well over a year ago. I'm just maintaining it for the community at this time.

Publishing to the Chrome Web Store was on the road map initially, but I ultimately opted against it ([see #14](https://github.com/kkkrist/chromium-notifier/issues/14#issuecomment-621166319)). If you want it on the store, feel free to fork and publish. Just leave the privacy proxy out or better yet host [your own](https://github.com/kkkrist/chromium-extension-service).

Regarding manifest v3: Last time I checked, updating was quite a bit more refactoring work than increasing `manifest_version`. So I thought, I'd better put it on hold and see how the whole v3 drama works out anyway. That's were I'm still at. Again, PRs would be greatly appreciated.

**Comment by Alex313031** [comment]
@kkkrist OK I made a pull request. Also, to publish it on your behalf, how would I remove the privacy proxy?? I also noticed you made a branch to try to make it work with manifest v3, what went wrong on that? It seems you made all the required changes?

**Comment by Alex313031** [comment]
@kkkrist Also, btw, releases should have the .crx in a .zip file. If you try to download the .crx in a chromium based browser it will complain with "CRX_REQUIRED_PROOF_MISSING" which happens when an extension either doesn't have an update url, or has one that is not the chrome web store's. All my extensions are on the web store, however on github I simply remove the update url line in the manifest.json, and then pack the .crx in a .zip so that it "hides" the fact that it is a crx from chromium.

For example like my release I made just now > https://github.com/Alex313031/chromium-notifier/releases/tag/v1.9.0

This change was introduced in chromium 90 to increase security to help prevent unintentional or malicious installation of extensions.

**Comment by kkkrist** [comment]
> Also, to publish it on your behalf, how would I remove the privacy proxy??

I think removing the checkbox from the popup UI and initializing `useProxy` with `false` in the `getConfig()` helper should be enough. Just keep in mind that `useProxy` being `undefined` equals to "enabled" for backwards-compatibility (this config param didn't exist in previous versions, the proxy was always on).

> I also noticed you made a branch to try to make it work with manifest v3, what went wrong on that? It seems you made all the required changes?

Honestly, I don't remember the details. It's been over a year ago and I didn't try very hard.

> Also, btw, releases should have the .crx in a .zip file. If you try to download the .crx in a chromium based browser it will complain with "CRX_REQUIRED_PROOF_MISSING" which happens when an extension either doesn't have an update url, or has one that is not the chrome web store's.

Yes, I know and it's one of the reasons I initially wanted to publish to the store. But some Chromium builds use the [`add-flag-to-configure-extension-downloading` patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-configure-extension-downloading.patch), allowing for one-click extension updates from within the popup. I always found it kind of neat and wrapping the crx into a (another) zip would disable it.

**Comment by Alex313031** [comment]
@kkkrist No what I'm saying, is publish the .crx by itself, as well as in a .zip. That way people can update the extension that way if they want to, or directly download the .crx in another browser, or, download the .zip, unpack it, and drag n' drop in chrome://extensions. A note could be made on the release explaining why there is a .crx and .zip together.

**Comment by kkkrist** [comment]
Oh, that sounds like a good idea. I'll do that with the next release.

**Comment by Alex313031** [comment]
@kkkrist The readme on github already says its a fork, but I will make sure the readme is inside the .crx, as well as modify the description.

Right now, Im going to work on migrating it to manifest v3. Im going to start with your changes, and then work from there. Because it will eventually need to be migrated, if users are to use this extension after 2023.

**Comment by Alex313031** [comment]
@kkkrist So I migrated it to manifest v3, and removed the proxy, and fixed a few more things in the .js files on top of what you did.
But I got stuck. Could you help. The issue is in utils.js. Shows this.
![Screenshot from 2022-07-02 11-14-33](https://user-images.githubusercontent.com/45863095/177009522-b82d4580-8f34-4c05-a6aa-798bf237db2e.png)

**Comment by kkkrist** [comment]
`DOMParser` is used to parse the XML responses from the extension update endpoints. It's a browser primitive that exists in Chrome since day 1. If I remember correctly, manifest v3 extension's background scripts are run in a service worker. Unfortunately, service workers don't have access to DOM-related primitives. So the XML needs to be parsed without `DOMParser` in order to be able to do it in a service worker. That's probably one of the main reasons I've put porting to manifest v3 on hold.

Btw, was it possible to rebase the v3 branch? It must have been quite old.

**Comment by Alex313031** [comment]
@kkkrist Yes I was able to rebase it, and get stuff to work, up until this point.

**Comment by Alex313031** [comment]
.noclose

**Comment by kkkrist** [comment]
Google has postponed turning off manifest v2 support until further notice:

https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E

My migration plan for v3 was to bundle up a 3rd-party js-based dom parser from node land for the service worker to use. I'll now take a look into the new Offscreen Documents API too. I'm still hesitant to switch to v3 for idealogical reasons though and will probably wait until the very last minute to make a decision.
